### ISSUE TITLE
LSM9DS1 

### ISSUE THREAD

**Issue by hellowtisch** [DavidEGrayson/minimu9-ahrs#32]
Hello, for the above LSM9DS1 I do receive the following error:
Error: No accelerometer found.
Error: No gyro found.
Error: Needed sensors are missing.

sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- 1e -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- 6b -- -- -- -- 
70: -- -- -- -- -- -- -- -- 

Is this sensor maybe not supported? I am using a SparkFun 9dof sensor stick.

**Comment by DavidEGrayson** [comment]
No.  The list of supported chips is displayed prominently in README.md:

https://github.com/DavidEGrayson/minimu9-ahrs
