### ISSUE TITLE
Issue with LSM303D 

### ISSUE THREAD

**Issue by jtoland** [DavidEGrayson/minimu9-ahrs#37]
Hello,

I am having a bit of an issue and was wondering if someone could help.

https://www.amazon.co.uk/LSM303D-6DoF-Motion-Sensor-Breakout/dp/B07GMHSZD9/ref=sr_1_1?keywords=LSM303D&qid=1582483640&sr=8-1

I have an LSM303D witch says is supported but i run minimu9-ahrs --mode raw i am getting the following error 

Error: No gyro found.
Error: Needed sensors are missing.

Is there any way to disable the gyro as I don't need that part.

Kind Regards,
Jason

**Comment by DavidEGrayson** [comment]
The man page describes all the options of minimu9-ahrs.  The one you should look into is `--compass-only`
