### ISSUE TITLE
Noob problem; don't know where to run the 'make' command 

### ISSUE THREAD

**Issue by PieterHerings** [DavidEGrayson/minimu9-ahrs#38]
Hi there,

As a beginner I am trying to install the minimu9-ahrs for the raw data. As I am walking through the steps, I face a slight problem. 

At the moment my sensor is soldered well and I get an output from i2cdetect -y 1. But I don't know how to navigate to the top-level directory and run the 'make' command. Where should I type this? How can I navigate to the good place in the terminal?

Thanks in advance

**Comment by DavidEGrayson** [comment]
Use the `cd` command to get into the directory where you downloaded the source code of this project.
