### ISSUE TITLE
Can't create ~./minimu9-ahrs: File exists

### ISSUE THREAD

**Issue by PieterHerings** [DavidEGrayson/minimu9-ahrs#40]
Hi,

Facing another small problem. I try to create a ~./minimu9-ahrs file in the home directory, but the terminal errors with ''mkdir: cannot create directory ' /home/pi/.minimu9-ahrs': File exists". 

I see in the source code various different minimu9-ahrs files and I don't know where to put the 'i2c-bus=/dev/i2c-1' line. Can you help me out again? 

Thanks in advance

**Comment by DavidEGrayson** [comment]
mkdir is not the right tool for creating a text file.  You can create .minimu9-ahrs with a text editor like nano.
