### ISSUE TITLE
png_texture.cpp:121:41: error: 'malloc' was not declared in this scope

### ISSUE THREAD

**Issue by PieterHerings** [DavidEGrayson/minimu9-ahrs#41]
Hi,

While running the 'sudo make install' I get this error message stated in the title.
I installed all the libraries, can you help me out what the problem is?

Thanks in advance

**Comment by DavidEGrayson** [comment]
You shouldn't be getting that kind of error when you run `sudo make install`.  That kind of error should happen at the earlier step when you simply run `make`.  Can you please run `make` and then post the full, entire output from your shell, including the command prompt where you typed `make`?
