### ISSUE TITLE
Using library in another project

### ISSUE THREAD

**Issue by nam-lu** [DavidEGrayson/minimu9-ahrs#45]
I was wondering if it is possible to include this library as a dependency in another C++ project and programmatically pull sensor data in code? 
I was able to get it working on the CLI but am not sure how to include it in my project. 
I'm new to C++ so I was trying to figure out if it was possible.

Thank you!

**Comment by DavidEGrayson** [comment]
This project is not designed to be a library, it's designed to be an executable program that you run at the command line.  So you should consider just using it the way it was meant to be used.  You can run it and read data from it using your C++ program, using the methods you would use to run any other command-line utillity.

If there's something you want to do that the command-line utility doesn't give you or you really just want to have a library, you might consider copying the source code files of interest to you into your project along with LICENSE.txt.
