### ISSUE TITLE
How to change GPIO pins?

### ISSUE THREAD

**Issue by HicBellator** [DavidEGrayson/minimu9-ahrs#47]
Using a different processing board and need to solder the gyro board to different GPIO pin numbers. How can the target pins be set within the code?

**Comment by DavidEGrayson** [comment]
The code in this project does not directly manipulate any GPIO pins.  It just connects to an I2C device provided by your kernel, such as `/dev/i2c-1`.  There is a command line option  for setting which bus to use, and you can also put it in a configuration file, as documented in the README here: https://github.com/DavidEGrayson/minimu9-ahrs#determining-which-bus-to-use

Also, this code only connects to one I2C bus and expects all devices to be there.

It's up to you to configure your kernel to use the right GPIO pins.  If you are using the Raspberry Pi, there is an "overaly" called "i2c-gpio" you can use to accomplish this.  I don't know of any great tutorials for it, but if you search around for keywords you should be able to figure out how to configure it.  Here is a relevant looking discussion: https://github.com/raspberrypi/firmware/issues/1401
